### ISSUE TITLE
CORS Error for Pasted Images

### ISSUE THREAD

**Issue by LawJolla** [ianstormtaylor/slate-drop-or-paste-images#8]
Again, great work!   Slate helps me immensely.

I'm not a CORS expert, so I'm not much help.  I see you've implemented some of this using Canvas -- yet another thing that I don't know. :)

The image-to-data-uri.js file has img cross origin attribute is set, so I assume the intention is to allow pasted links from other websites.

When copy and pasting images to the demo site (https://ianstormtaylor.github.io/slate-drop-or-paste-images/), the image must be from Github or the browser throws a CORS error and refuses the load.  E.g.

https://octodex.github.com/images/mcefeeline.jpg
Works

http://www.pngmart.com/files/1/Cat-PNG-File-337x279.png
Fails, CORS.

This behavior occurred on all current versions of Safari, Firefox, and Chrome.

**Comment by dmitrizzle** [comment]
Can replicate. I'd imagine the right way to fix this would be to set up a back-end proxy to download the images. Or not convert them to `data-uri` at all

**Comment by oyeanuj** [comment]
@LawJolla Essentially, the image(/url) that you use has to have the right CORS setting. For example, when using this image (https://assets.imgix.net/unsplash/raspberries.jpg?w=900&usm=10&fm=pjpg&q=95) it works well.

**Comment by ianstormtaylor** [comment]
Yeah, unfortunately it depends on the CORS headers that the image is served with, and there's no way around this with purely client-side logic. If you want to reliably be able to download the images always, you'll need a server-side component I believe.

**Comment by dmitrizzle** [comment]
I'm building code in node that will download images from remote websites onto server. Yet to see how it will react to CORS headers, but I'm optimistic. Will post link to code or snippet when done if anyone is interested.

**Comment by ianstormtaylor** [comment]
Nice, thanks @dmitrizzle!
